name: Test Rust Projects

env:
  TARGET_DIR: "2023/1-1-trebuchet"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Cargo Test
    uses: .github/workflows/templates/carg-test.yml
    env:
      TARGET_DIR: $TARGET_DIR
