name: Zig Build and Test
inputs:
  target_dir:
    description: 'Folder to run action against'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Up Zig
      uses: goto-bus-stop/setup-zig@v2
    - name: Build
      shell: bash
      working-directory: ${{ inputs.target_dir }}
      run: zig build
    - name: Run tests
      shell: bash
      working-directory: ${{ inputs.target_dir }}
      run: zig build test