name: Golang build and test
inputs:
  target_dir:
    description:
      required: true

runs:
  using: "composite"
  steps:
    - name: Set Up Golang
      uses: actions/setup-go@v4
      with:
        go-version: "1.21.5"
    - name: Install Dependencies
      shell: bash
      working-directory: ${{ inputs.target_dir }}
      run: go get .
    - name: Run Tests
      shell: bash
      working-directory: ${{ inputs.target_dir }}
      run: go test
