name: Cargo Test
inputs:
  target-dir:
    description: 'Folder to run action against'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run tests
      shell: bash
      run: cargo test --verbose ${{ inputs.target-dir }}