name: CMake Test
inputs:
  target_dir:
    description: 'Folder to run action against'
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure CMake
      shell: bash
      run: cmake -B ${{ inputs.target_dir }}/build ${{ inputs.target_dir }}
    - name: Build
      shell: bash
      run: cmake --build ${{ inputs.target_dir }}/build
    - name: Test
      shell: bash
      working-directory: ${{ inputs.target_dir }}/build
      run: ctest