name: CMake Test
inputs:
  target_dir:
    description: 'Folder to run action against'
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure CMake
      shell: bash
      run: cmake -B ${{github.workspace}}/build ${{ inputs.target_dir }}
    - name: Build
      shell: bash
      run: cmake --build ${{github.workspace}}/build
    - name: Test
      shell: bash
      working-directory: ${{ github.workspace }}/build
      run: ctest