name: CMake Test
inputs:
  target-dir:
    description: 'Folder to run action against'
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build ${{ inputs.target-dir }}
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Test
      run: ctest