name: CMake Test
inputs:
  target-dir:
    description: 'Folder to run action against'
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure CMake
      shell: bash
      run: cmake -B ${{github.workspace}}/build ${{ inputs.target-dir }}
    - name: Build
      shell: bash
      run: cmake --build ${{github.workspace}}/build
    - name: Test
      shell: bash
      working-directory: ${{ github.workspace }}/build
      run: ctest
    - name: debug
      shell: bash
      run: pwd && tree
    - name: Run Final Test
      shell: bash
      run: ${{github.workspace}}/build/cube_conundrum ./input-file
