name: Test Cubes Part 1

env:
  TARGET_DIR: './2023/02-cubes/part-1'
  ANSWER: '2528'

on:
  pull_request:
    paths:
      - '2023/02-cubes/part-1/**'
  workflow_dispatch:

jobs:
  build:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run ctest
        uses: ./.github/workflows/templates/cmake-test
        with:
          target-dir: ${{ env.TARGET_DIR }}

      - name: Check Final Answer
        shell: bash
        working-directory: ${{ env.TARGET_DIR }}
        run: "${{github.workspace}}/build/cube_conundrum ./input-data | awk '/Answer: ${{ env.ANSWER }}/{found=1; exit} END{exit !found}'"

