name: Test Cubes Part 1

env:
  TARGET_DIR: './2023/02-cubes/part-2'
  ANSWER: '' #TODO

on:
  pull_request:
    paths:
      - '2023/02-cubes/part-2/**'
      - '.github/workflows/templates/cmake-test/**'
      - '.github/workflows/2-2-cubes.yml'
  workflow_dispatch:

jobs:
  build:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run ctest
        uses: ./.github/workflows/templates/cmake-test
        with:
          target_dir: ${{ env.TARGET_DIR }}

      - name: Check Final Answer
        uses: ./.github/workflows/templates/final-answer
        with:
          target_dir: ${{ env.TARGET_DIR }}
          executable: ./build/cube_conundrum
          input_data: ./input-data
          expected_result: "Answer: 67363"