name: Test Rust Projects

env:
  TARGET_DIR: '2023/1-1-trebuchet'

on:
  push:
    branches: [ "main" ]
    paths:
      - '${{ env.TARGET_DIR }}/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '${{ env.TARGET_DIR }}/**'

jobs:
  build:
    name: 'Build and Test Rust'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Cargo Test
        uses: ./.github/workflows/templates/cargo-test
        with:
          target-dir: ${{ env.TARGET_DIR }}