name: Test Rust Projects

env:
  TARGET_DIR: "2023/1-1-trebuchet"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Cargo Test
        uses: .github/workflows/templates/cargo-test.yml
        env:
          TARGET_DIR: $TARGET_DIR